colorBlockMap:
  '000000': BLACK_CONCRETE
  '808080': GRAY_CONCRETE
  'C0C0C0': LIGHT_GRAY_CONCRETE
  'FFFFFF': WHITE_CONCRETE
  '654321': BROWN_TERRACOTTA
  'FF0000': RED_WOOL
  'FFA500': ORANGE_TERRACOTTA
  'FFFF00': YELLOW_WOOL
  '008000': GREEN_WOOL
  '00FF00': LIME_WOOL
  '0000FF': BLUE_WOOL
  'ADD8E6': LIGHT_BLUE_CONCRETE
  '800080': PURPLE_WOOL
  'FF00FF': MAGENTA_WOOL
  'FFC0CB': PINK_WOOL
  '40E0D0': CYAN_WOOL
  '00FFFF': LIGHT_BLUE_CONCRETE
  'A9A9A9': GRAY_TERRACOTTA
  '8B4513': DARK_OAK_PLANKS
  'CD853F': ACACIA_PLANKS
  'A0522D': JUNGLE_PLANKS